-- MySQL Script generated by MySQL Workbench
-- Mon May 25 18:52:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delilah
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `delilah` ;

-- -----------------------------------------------------
-- Schema delilah
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delilah` DEFAULT CHARACTER SET utf8 ;
USE `delilah` ;

-- -----------------------------------------------------
-- Table `delilah`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`rol` ;

CREATE TABLE IF NOT EXISTS `delilah`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`usuario` ;

CREATE TABLE IF NOT EXISTS `delilah`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(60) NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_rol`),
  INDEX `fk_Usuarios_Roles1_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `delilah`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`estado_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`estado_pedido` ;

CREATE TABLE IF NOT EXISTS `delilah`.`estado_pedido` (
  `id_estado_pedido` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`forma_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`forma_pago` ;

CREATE TABLE IF NOT EXISTS `delilah`.`forma_pago` (
  `id_forma_pago` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_forma_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`pedido` ;

CREATE TABLE IF NOT EXISTS `delilah`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `valor_total` DECIMAL(10,2) NULL,
  `fecha_pedido` DATETIME NULL,
  `id_usuario` INT NOT NULL,
  `id_estado_pedido` INT NOT NULL,
  `id_formas_pago` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_usuario`, `id_estado_pedido`, `id_formas_pago`),
  INDEX `fk_Pedidos_Usuarios_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_Pedidos_EstadosPedido1_idx` (`id_estado_pedido` ASC) VISIBLE,
  INDEX `fk_Pedidos_FormasPago1_idx` (`id_formas_pago` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `delilah`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_EstadosPedido1`
    FOREIGN KEY (`id_estado_pedido`)
    REFERENCES `delilah`.`estado_pedido` (`id_estado_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_FormasPago1`
    FOREIGN KEY (`id_formas_pago`)
    REFERENCES `delilah`.`forma_pago` (`id_forma_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`permiso` ;

CREATE TABLE IF NOT EXISTS `delilah`.`permiso` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `recurso` VARCHAR(45) NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_permiso`, `id_rol`),
  INDEX `fk_Permisos_Roles1_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_Permisos_Roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `delilah`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`item` ;

CREATE TABLE IF NOT EXISTS `delilah`.`item` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `imagen` VARCHAR(70) NULL,
  PRIMARY KEY (`id_item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`factura` ;

CREATE TABLE IF NOT EXISTS `delilah`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `id_pedidos` INT NOT NULL,
  `id_items` INT NOT NULL,
  PRIMARY KEY (`id_factura`, `id_pedidos`, `id_items`),
  INDEX `fk_Factura_Pedidos1_idx` (`id_pedidos` ASC) VISIBLE,
  INDEX `fk_Factura_Items1_idx` (`id_items` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Pedidos1`
    FOREIGN KEY (`id_pedidos`)
    REFERENCES `delilah`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Items1`
    FOREIGN KEY (`id_items`)
    REFERENCES `delilah`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`usuario_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`usuario_item` ;

CREATE TABLE IF NOT EXISTS `delilah`.`usuario_item` (
  `id_usuario_item` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_item` INT NOT NULL,
  PRIMARY KEY (`id_usuario_item`, `id_usuario`, `id_item`),
  INDEX `fk_UsuariosItems_Usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_UsuariosItems_Items1_idx` (`id_item` ASC) VISIBLE,
  CONSTRAINT `fk_UsuariosItems_Usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `delilah`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuariosItems_Items1`
    FOREIGN KEY (`id_item`)
    REFERENCES `delilah`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insert Data
-- -----------------------------------------------------

INSERT INTO `delilah`.`rol` (`descripcion`) VALUES ('Admin'),('Customer');
INSERT INTO `delilah`.`forma_pago` (`descripcion`) VALUES ('Efectivo');
INSERT INTO `delilah`.`forma_pago` (`descripcion`) VALUES ('PSE');
INSERT INTO `delilah`.`forma_pago` (`descripcion`) VALUES ('Tarjeta de Credito');
INSERT INTO `delilah`.`forma_pago` (`descripcion`) VALUES ('Tarjeta Debito');
INSERT INTO `delilah`.`usuario` (`login`, `nombre`, `apellido`, `correo`, `telefono`, `direccion`, `password`, `fecha_registro`, `id_rol`) VALUES ('admin', 'admin', 'test', 'admin@test.com', '1234567890', 'Av 21 #23-12', '123', '2020-05-26', '1');
INSERT INTO `delilah`.`usuario` (`login`, `nombre`, `apellido`, `correo`, `telefono`, `direccion`, `password`, `fecha_registro`, `id_rol`) VALUES ('customer', 'customer', 'test', 'customer@test.com', '1234567890', 'Av 21 #23-12', '123', '2020-05-26', '2');
INSERT INTO `delilah`.`item` (`nombre`, `descripcion`, `valor`) VALUES ('Ponque', 'Ponque redondo 6 porciones', '3000');
INSERT INTO `delilah`.`item` (`nombre`, `descripcion`, `valor`) VALUES ('Gaseosa 250ml', 'Gaseosa personal', '2000');
INSERT INTO `delilah`.`estado_pedido` (`descripcion`, `color`) VALUES ('Nuevo', 'Rojo');
INSERT INTO `delilah`.`estado_pedido` (`descripcion`, `color`) VALUES ('Confirmado', 'Naranja');
INSERT INTO `delilah`.`estado_pedido` (`descripcion`, `color`) VALUES ('Preparando', 'Amarillo');
INSERT INTO `delilah`.`estado_pedido` (`descripcion`, `color`) VALUES ('Enviado', 'Verde');
INSERT INTO `delilah`.`estado_pedido` (`descripcion`, `color`) VALUES ('Cancelado', 'Purpura');
INSERT INTO `delilah`.`estado_pedido` (`descripcion`, `color`) VALUES ('Entregado', 'Gris');

